---
title: "Behavioral Data Analysis"
output: html_document
date: "2024-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## load library
```{r}
# Load required R packages
library(nlme)       # For fitting linear and nonlinear mixed-effects models
library(ggplot2)    # For data visualization
library(emmeans)    # For estimated marginal means (least-squares means)
library(sjPlot)     # For data visualization and tables
library(tidyverse)  # Collection of R packages for data manipulation and visualization
library(lme4)       # For linear mixed-effects models
library(car)        # For regression diagnostics and other statistical functions

# Display R version information
R.version.string

# Display package versions
packageVersion("nlme")
packageVersion("ggplot2")
packageVersion("emmeans")
packageVersion("sjPlot")
packageVersion("tidyverse")
packageVersion("lme4")
packageVersion("car")

# To get versions of all loaded packages
installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
```
## color setting
```{r}
memory_color = '#4573e0'
arousal_color = '#45b4af'
cortisol_color ='#e06545'
placebo_color = '#b44582' 

```


## cortisol data
```{r}
# read CSV
dat_cort <- read.csv("data/behavior/cortisol_data.csv")

# drop NA values in Avg
dat_cort <- na.omit(dat_cort)

# dotplot
p<-ggplot(dat_cort, aes(x = desc, y = Avg, fill = Condition)) +
  geom_boxplot(position = position_dodge(width =1),
               alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(aes(fill = Condition),
               binaxis = "y", stackdir = "center",
               dotsize = 0.7, binwidth = 0.3,
               alpha = 0.5, stroke = 0,   # remove outlines
               position = position_dodge(width = 1)) +
  scale_fill_manual(values = c("Cortisol" = cortisol_color, "Placebo" = placebo_color)) +
  scale_x_discrete(labels = c("baseline", "post_drug", "post-encoding")) +
  labs(x = "", y = "cortisol: nmol/L") +
  theme_classic() +
  theme(
    legend.title = element_blank(),
    legend.position = "right"
  )
p
ggsave("plots/Fig1_cortisol_level.png", p, width = 8, height = 5)
ggsave("plots/Fig1_cortisol_level.pdf", p, width = 8, height = 5)

```

## behavior data loading
```{r}
filename='data/behavior/mem_allsub_alltrial_pill.csv'
dat<-data.frame(read.csv(filename))
# data cleaning 
dat<-dat %>%
        mutate(RecogAcc_coded = ifelse(RecogAcc==4,0,ifelse(RecogAcc==1,1,NA)),
               Stim = ifelse(Stim=='alc','Emotional',ifelse(Stim=='tool','Neutral',NA))
               )
# exclude subj with incomplete data
dat<-dat[dat$Subject!="9029",]
dat$RecogAcc_coded<-factor(dat$RecogAcc_coded)
dat$Stim<-factor(dat$Stim)
dat$Pill<-factor(dat$Pill)
dat<-dat[!is.na(dat$Arous_All),]
dat<-dat[!is.na(dat$RecogAcc_coded),]
# re-code encoding trial to 1-80
dat$enctrial_cont<-(dat$StimOrd-1)*40+dat$Enc_Trial
```

## Main text:Effects of cortisol on emotional memory
```{r} 
# variable names:
dat1<-dat %>%
        mutate(RecogAcc_coded = ifelse(RecogAcc_coded==0,'F',ifelse(RecogAcc_coded==1,'R',NA)),
      RecogAcc_coded = factor(RecogAcc_coded, levels = c("R", "F"))
               )
# 2way interaction - interaction of pill and memory on arousal
m<-lme(Arous_All ~ enctrial_cont+Stim+Pill*RecogAcc_coded,random=~1 | Subject,data=dat1)
twoway_anova<-anova(m, type='marginal')
print(twoway_anova["Pill:RecogAcc_coded",])
t_test<-test(emmeans(m, pairwise ~ RecogAcc_coded|Pill))
print(t_test)
#mean & sd
dat1 %>%
  group_by(Pill, RecogAcc_coded) %>%
  summarise(
    mean_Arous = mean(Arous_All, na.rm = TRUE),
    sd_Arous   = sd(Arous_All, na.rm = TRUE),
    n          = n(),
    .groups = "drop"
  )

# plot figure 1 - cortisol effect on arousing memory
p<-plot_model(m,type="eff",terms=c("Pill","RecogAcc_coded"),colors=c(adjustcolor( memory_color, alpha.f = 0.4),adjustcolor( memory_color, alpha.f = 1),memory_color),dodge = .5, ci.lvl = .95, title = "")+  labs(x = "", y = "Arousal",colour="Memory") + theme_classic()  +theme(
    axis.title = element_text(size = 14,face = "bold"),    # Axis labels
    axis.text = element_text(size = 12),     # Axis tick labels
    legend.title = element_text(size = 14),  # Legend title
    legend.text = element_text(size = 14),    # Legend labels
    strip.text = element_text(size = 14)  # Panel titles
  )
p

ggsave("plots/Fig1_arousing_memory.png", p, width = 8, height = 4)
ggsave("plots/Fig1_arousing_memory.pdf", p, width = 8, height = 4)


# 3way interaction - between Memory, Pill, and Run
# "This interaction was particularly evident during emotional runs (run x pill x memory: F(1,4007) = 7.20, p = .007; Figure S1A)."
m<-lme(Arous_All ~ enctrial_cont+Stim*Pill*RecogAcc_coded,random=~1 | Subject,data=dat1)
threeway_anova<-anova(m,type='marginal')
threeway_anova["Stim:Pill:RecogAcc_coded",]

# plot figure S1A
p<-plot_model(m,type="eff",terms=c("Pill","RecogAcc_coded","Stim"),colors=c(adjustcolor( memory_color, alpha.f = 0.4),adjustcolor( memory_color, alpha.f = 1),memory_color),dodge = .5, ci.lvl = .95, title = "")+  labs(x = "", y = "Arousal",colour="Memory") + theme_classic()  +theme(
    axis.title = element_text(size = 14,face = "bold"),    # Axis labels
    axis.text = element_text(size = 12),     # Axis tick labels
    legend.title = element_text(size = 14),  # Legend title
    legend.text = element_text(size = 14),    # Legend labels
    strip.text = element_text(size = 14)  # Panel titles
  )
ggsave("plots/FigS1_arousing_memory_byRun.png", p, width = 8, height = 4)
ggsave("plots/FigS1_arousing_memory_byRun.pdf", p, width = 8, height = 4)

```

## Supplement: behavioral data - arousal
```{r}
# main effect of pill and stim on arousal
# "We found that participants rated object/scene pairs as marginally more arousing under placebo (main effect pill: F(1, 4012) = 3.32, p = .07) and significantly more arousing during emotional runs (main effect run type: F(1,4012) = 56.30, p < .0001). "

m<-lme(Arous_All ~ Pill+Stim+enctrial_cont,random=~1 | Subject, data=dat, na.action=na.omit)
maineffect_arousal<-anova(m,type='marginal')
print(maineffect_arousal[c("Pill", "Stim"),])

#mean & sd by Pill
dat1 %>%
  group_by(Pill) %>%
  summarise(
    mean_Arous = mean(Arous_All, na.rm = TRUE),
    sd_Arous   = sd(Arous_All, na.rm = TRUE),
    n          = n(),
    .groups = "drop"
  )

#mean & sd by Run
dat1 %>%
  group_by(Stim) %>%
  summarise(
    mean_Arous = mean(Arous_All, na.rm = TRUE),
    sd_Arous   = sd(Arous_All, na.rm = TRUE),
    n          = n(),
    .groups = "drop"
  )

# simple and interaction effect of pill and stim on arousal
# "In a separate model that allowed for interactions between pill and run type, we found that this boost in arousal for emotional runs was more evident under placebo conditions (Pill x Run: F(1,4011) = 4.21, p = .04; emotional cortisol vs emotional placebo: t(4011) = -2.74, p = .03； Fig S1B)."
m<-lme(Arous_All ~ Pill*Stim+enctrial_cont,random=~1 | Subject, data=dat, na.action=na.omit)
interaction_arousal<-anova(m,type='marginal')
print(interaction_arousal[c("Pill:Stim"),])
contrast_arousal<-test(emmeans(m, pairwise~ Pill:Stim))
print(contrast_arousal$contrasts[grep("Cortisol Emotional - Placebo Emotional", contrast_arousal$contrasts$contrast), ])

# mean & sd
dat1 %>%
  group_by(Pill,Stim) %>%
  summarise(
    mean_Arous = mean(Arous_All, na.rm = TRUE),
    sd_Arous   = sd(Arous_All, na.rm = TRUE),
    n          = n(),
    .groups = "drop"
  )

# create figure S1B
p<-plot_model(m,type="eff",terms=c("Stim","Pill"),ci.lvl = .95) +scale_color_manual(  name="",labels=c("Cortisol", "Placebo"),values = c(cortisol_color, placebo_color)) +labs(x = "", y = "Arousal",title="")  +theme_classic()+theme(
    axis.title = element_text(size = 14,face = "bold"),    # Axis labels
    axis.text = element_text(size = 12),     # Axis tick labels
    legend.title = element_text(size = 14),  # Legend title
    legend.text = element_text(size = 14),    # Legend labels
    strip.text = element_text(size = 14)  # Panel titles
  )
ggsave("plots/FigS1_arousing.png", p, width = 8, height = 4)
ggsave("plots/FigS1_arousing.pdf", p, width = 8, height = 4)
p

```

## Supplement: behavioral data - memory
```{r}
# "In contrast, there were no significant differences in memory based on run or pill (all p > 0.05)."

# main effect of pill and stim on mem
m<-glmer(RecogAcc_coded ~ Pill+Stim+enctrial_cont+(1|Subject)+StimOrd, family=binomial, data=dat)
print(Anova(m,type="II"))

# simple and interaction effect of pill and stim on mem
m<-glmer(RecogAcc_coded ~ Pill*Stim+enctrial_cont+(1|Subject), family=binomial, data=dat)
print(Anova(m,type="II"))

```

## reply to reviewer
```{r}
#alternative, predicting memory with arousal
dat1$RecogAcc_coded<-factor(dat1$RecogAcc_coded)
dat1$Pill <- relevel(factor(dat1$Pill), ref = "Cortisol")
dat1 <- dat1 %>% 
  mutate(EmoFirst = ifelse(StimOrd==1 & Stim=="Emotional", 'Y', 'N'),
        RecogAcc_coded = factor(RecogAcc_coded, levels = c("F","R")))

m_glm <- glmer(
     RecogAcc_coded ~ Arous_All*Pill+Stim + enctrial_cont + (1 | Subject),
     data = dat1,
     family = binomial(link = "logit")
 )
twoway_anova<-Anova(m_glm, type='II')
print(twoway_anova["Arous_All:Pill",])
test(emtrends(m_glm, pairwise ~ Pill, var = "Arous_All"))
p<-plot_model(m_glm,type="eff",terms=c("Pill","Arous_All"),title="")+  labs(x = "", y = "Memory",colour="Arousal") + theme_classic()  +theme(
    axis.title = element_text(size = 14,face = "bold"),    # Axis labels
    axis.text = element_text(size = 12),     # Axis tick labels
    legend.title = element_text(size = 14),  # Legend title
    legend.text = element_text(size = 14),    # Legend labels
    strip.text = element_text(size = 14)  # Panel titles
  )
ggsave("plots/ReviewReply_predicting_memory.png", p, width = 8, height = 4)
ggsave("plots/ReviewReply_predicting_memory.pdf", p, width = 8, height = 4)

# order effect on memory
# order of emotional stimuli

m.mem.order = glmer(RecogAcc_coded ~ enctrial_cont+EmoFirst+Week+ (1 | Subject),family=binomial,data=dat)
print(Anova(m.mem.order, type = "2"))

m.mem.order.pill = glmer(RecogAcc_coded ~ Pill*(enctrial_cont+EmoFirst+Week)+ (1 | Subject),family=binomial,data=dat)
print(Anova(m.mem.order.pill, type = "2"))

# arousal distribution 
ggplot(dat1, aes(x = factor(Arous_All), fill = Pill)) +
    geom_bar(position = "dodge", color = "black") +
    facet_wrap(~ Stim, nrow = 1) +   # only 2 panels: Emotional vs Neutral
    scale_fill_manual(values = c("Cortisol" = "#e06545", 
                                 "Placebo" = "#b44582")) +
    labs(
        x = "Arousal Rating",
        y = "Count"
    ) +
    theme_minimal(base_size = 14) +
    theme(
        strip.text = element_text(size = 14, face = "bold"), # Emotional/Neutral labels
        legend.title = element_blank(),                      # clean legend
        panel.grid.major.x = element_blank(),
        plot.title = element_blank()                         # removes title
    )

ggsave("plots/ReviewReply_arousal_distribution.png", p, width = 8, height = 4)
ggsave("plots/ReviewReply_arousal_distribution.pdf", p, width = 8, height = 4)
```
